package com.codeAvengers.quizProject.Model;


// QuizMaster - is our entity
// the POJO will be persisted into the database which is the h2-console

import javax.persistence.*;

@Entity
@Table(name = "QuizMaster")
public class QuizMaster {

    // attributes to be persisted into the data base
    // Id will be autogenerated
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Long id;

    @Column(name = "firstName")
    private String firstName;

    @Column(name = "lastName")
    private String lastName;

    @Column(name = "email")
    private String email;

    // task pending - improve the one to one relationship




    public QuizMaster() {
    }

    public QuizMaster(String firstName, String lastName, String email) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;

    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }


}



